mysql5.5:
  image: mysql:5.5
  container_name: mysql5.5
  ports:
    - 3355:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mysql5.5/conf.d:/etc/mysql/conf.d
mysql5.6:
  image: mysql:5.6
  container_name: mysql5.6
  ports:
    - 3356:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mysql5.6/conf.d:/etc/mysql/conf.d
mysql5.7:
  image: mysql:5.7
  container_name: mysql5.7
  ports:
    - 3357:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mysql5.7/conf.d:/etc/mysql/conf.d
mysql8.0:
  image: mysql:8.0
  container_name: mysql8.0
  ports:
    - 3380:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mysql8.0/conf.d:/etc/mysql/conf.d

mariadb10.0:
  image: mariadb:10.0
  container_name: mariadb10.0
  ports:
    - 3310:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mariadb10.0/conf.d:/etc/mysql/conf.d
mariadb10.1:
  image: mariadb:10.1
  container_name: mariadb10.1
  ports:
    - 3311:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mariadb10.1/conf.d:/etc/mysql/conf.d
mariadb10.2:
  image: mariadb:10.2
  container_name: mariadb10.2
  ports:
    - 3312:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mariadb10.2/conf.d:/etc/mysql/conf.d
mariadb10.3:
  image: mariadb:10.3
  container_name: mariadb10.3
  ports:
    - 3313:3306
  environment:
    - MYSQL_DATABASE=work
    - MYSQL_USER=worker
    - MYSQL_PASSWORD=worker
    - MYSQL_ROOT_PASSWORD=root
    - TZ=UTC
  volumes:
    - ./mariadb10.3/conf.d:/etc/mysql/conf.d
