CREATE TABLE IF NOT EXISTS tb2(
	id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE KEY,
  sex ENUM('1','2','3') DEFAULT '3',
	age TINYINT NOT NULL,
	KEY age (age)
	);
