CREATE TABLE IF NOT EXISTS tb6(
	id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(10) NOT NULL,
	pid SMALLINT UNSIGNED,
	FOREIGN KEY (pid) REFERENCES tb4 (id) ON DELETE NO ACTION 
	);

