version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=dev123456
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev123
      - MYSQL_DATABASE=testdb
      - LANG=C.UTF-8 #支持docker命令终端输入中文
    volumes:
      - ./conf/:/etc/mysql/conf.d/
      - ../sqls/:/sqls/
      - ./data:/var/lib/mysql #挂载数据目录, 每次重启后老数据依然保留

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
