# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

	config.vm.network "private_network", type:"dhcp"
	config.vm.define "centos7"
	config.vm.provider "virtualbox" do |vb|
		vb.name = "centos7"
	end
	config.vm.hostname = "centos7"

	# Vagrant provision shell with root privilege
	# set privileged true
end
